### ISSUE TITLE
[Design] Do we need NULL version of feature driver so that platform can has their own implementation?

### ISSUE THREAD

**Issue by nicklela** [tianocore/edk2-redfish-client#13]
OpenBMC utilize IPMI chassis command to get/set system bios boot options. Can we still support /redfish/v1/systems/sys/bios without having computer system collection and computer system driver?

**Comment by changab** [comment]
Or they can just have their library in platform DSC?

**Comment by nicklela** [comment]
Library will work but we may need to define the hook mechanism for feature driver

**Comment by nicklela** [comment]
We enhance `RedfishClientPkg\Library\RedfishResourceIdentifyLibComuterSystem\v1_5_0\RedfishResourceIdentifyLibComuterSystem.c` to accept the system ID from PCD and address this issue.
